name: "publish-sourcegraph-extension"

on:
  push:
    branches: [ main, release/* ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: yarn install
      - name: fetch-src-cli
        run: curl -L https://sourcegraph.example.com/.api/src-cli/src_linux_amd64 -o ./src && chmod +x ./src
      - name: publish
        uses: docker://sourcegraph/src-cli:3.29.1
        env:
          SRC_ENDPOINT: https://sourcegraph.com
          SRC_ACCESS_TOKEN: ${{ secrets.SOURCEGRAPH_ACCESS_TOKEN }}
        run: src publish
